name: "Integration"

env:
  COVERAGE_GIT_BRANCH: "main"
  COVERAGE_SERVICE_NAME: "github-actions-ci"
  ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  run-integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "yarn"
          node-version: "16"

      - name: "Install the dependencies"
        run: "yarn install --immutable"

      - name: "Lint Solidity and TypeScript code"
        run: "yarn lint"

      - name: "Compile the contracts and generate TypeChain bindings"
        run: "yarn compile"

      - name: "Test the contracts and run test coverage"
        run: "yarn coverage"

      - name: "Prepare coverage report"
        uses: "coverallsapp/github-action@master"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          path-to-lcov: "./coverage/lcov.info"

  upload-coverage-report:
    needs:
      - "run-integration"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Upload coverage reports to Coveralls"
        uses: "coverallsapp/github-action@master"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
